name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    services:
#      memcached:
#        image: memcached:1.6-alpine
#        ports:
#          - 11211:11211
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: quest_hunt_dev
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
#      redis:
#        image: redis:5.0
#        ports:
#          - 6379:6379
#        options: --entrypoint redis-server
#      dynamodb:
#        image: amazon/dynamodb-local:latest
#        ports:
#          - 8888:8000

    strategy:
      fail-fast: true
      matrix:
        php: ['8.2', '8.3']
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis-phpredis/phpredis@5.3.5, igbinary, msgpack, lzf, zstd, lz4, memcached
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none
        env:
          REDIS_CONFIGURE_OPTS: --enable-redis --enable-redis-igbinary --enable-redis-msgpack --enable-redis-lzf --with-liblzf --enable-redis-zstd --with-libzstd --enable-redis-lz4 --with-liblz4
          REDIS_LIBS: liblz4-dev, liblzf-dev, libzstd-dev

      - name: Set Minimum PHP 8.2 Versions
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require laravel/framework"^11.0 --no-interaction --no-update
        if: matrix.php >= 8.2

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

#      - name: Execute tests
#        run: vendor/bin/phpunit --verbose
#        env:
#          DB_PORT: ${{ job.services.mysql.ports[3306] }}
#          DB_USERNAME: root
#          DYNAMODB_CACHE_TABLE: laravel_dynamodb_test
#          DYNAMODB_ENDPOINT: "http://localhost:8888"
#          AWS_ACCESS_KEY_ID: random_key
#          AWS_SECRET_ACCESS_KEY: random_secret

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            vendor/orchestra/testbench-core/laravel/storage/logs
            !vendor/**/.gitignore
